#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

echo "Cleaning logfiles*"
rm log.*
echo "Cleaning polyMesh/"
rm -r constant/polyMesh
echo "Cleaning postProcessing/"
rm -r postProcessing
echo "Cleaning torch *.pt"
rm *.pt