#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=dfHighSpeedFoam

cp -r 0_orig/ 0/
runApplication blockMesh
runApplication setFields
runApplication decomposePar
runApplication mpirun -np 4 $application -parallel
